### ISSUE TITLE
Publish latest updates to Pypi

### ISSUE THREAD

**Issue by trypolis464** [accessibleapps/accessible_output2#10]
There have been a few PRs merged lately, EG fixing the stupid genpy crap, that are really useful. Currently to use these new features, I have to fork the repo and manually install it. It would be really nice if
```batch
pip install accessible_output2
```
Installed a version with these fixes.

**Comment by soundmud** [comment]
Even without updating to Pypi it's already possible to use this command:
`pip` install git+https://github.com/accessibleapps/accessible_output2

And you can use this line in a requirements.txt file:
`git+https://github.com/accessibleapps/accessible_output2`

**Comment by trypsynth** [comment]
That works, but the users shouldn't have to install from your git repo to get fixes that were added well over a year ago.

**Comment by trypsynth** [comment]
0.17 was pushed to Pypi, so I vote for marking this as closed.
