### ISSUE TITLE
Braille does not display when announcing a message with NVDA.

### ISSUE THREAD

**Issue by Nael-Sayegh** [accessibleapps/accessible_output2#19]
Hello,
I have tried using the library with Python 3.11 and NVDA 2023.3.
Here is a snippet of code:
`import accessible_output2.outputs.auto

message=accessible_output2.outputs.auto.Auto()
message.output("Test de vocalisationn")`
When I run this code, NVDA does pronounce the message correctly, but the braille display does not show it.
I tried using the braille function, but even there the message is not displayed.

**Comment by EphDoering** [comment]
I also experienced an issue with the combination of Auto and output, but it worked fine with braille.

Looking into the auto output function it only calls the speak function on the first available output. So braille not working with auto output makes sense.

Further looking into the output function on the base class, it seems to expect a return value from either the speak function or braille function, and none of those functions seem to actually return anything so it always raises an error even if both outputs work.

**Comment by Nael-Sayegh** [comment]
Hello @EphDoering,
In fact, the Braille display issue was due to a problem in my configuration. Thank you for your response and the PR you opened for the other issue you noticed.
